# fly.toml app configuration file generated for jizendo on 2025-05-13T17:23:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pigu'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3012
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3012
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = '1m0s'
    timeout = '5s'
    grace_period = '10s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '10s'
    method = 'get'
    path = '/'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1